### ISSUE TITLE
Tab completion Directory

### ISSUE THREAD

**Issue by nevadarain** [nodesocket/cryptr#4]
I am running kali linux and just want to make sure where to put "cryptr-bash-completion.bash".  Do i put in the in the location "/usr/share/bash-completion" folder or /etc/ folder?

**Comment by nodesocket** [comment]
I'm not exactly sure. According to [this SO post try](https://unix.stackexchange.com/questions/1800/how-to-specify-a-custom-autocomplete-for-specific-commands) `/etc/bash_completion.d/`.
