### ISSUE TITLE
Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by telltokichu** [nodesocket/cryptr#5]
I have to use cryptr in my React App but I'm getting this error - PFA
Help.
Thanks in advance.

<img width="1434" alt="Screenshot 2020-04-29 at 4 43 56 PM" src="https://user-images.githubusercontent.com/25656723/80589969-beac8380-8a38-11ea-9dec-6b7c15c7e78b.png">

**Comment by nodesocket** [comment]
Cryptr is a bash script, not sure how you using it in an React App?

**Comment by telltokichu** [comment]
Got it !
seems like cryptr is just a wrapper around the node core crypto module.
Which is not available in the browser and It is not designed to work in a browser or react application.
Thanks
