### ISSUE TITLE
Unable to encrypt file

### ISSUE THREAD

**Issue by KeakaR** [nodesocket/cryptr#7]
Hello,

I maybe stupid, but I am having trouble understanding how to encrypt a file.. I have tried to encrypt a file as shown in the example with no success?? 

Please help.

**Comment by nodesocket** [comment]
What is the error you are getting? Can you show the full output from:

```
cryptr encrypt <your-file-path-here>
```

**Comment by KeakaR** [comment]
Hi Justin,

Thank you for your quick response.  I figured it out. I didn’t have the path correct. 

Works perfect !!

Jack





“The belief in a supernatural source of evil is not necessary; men alone are quite capable of every wickedness."


Joesph Conrad









Sent with Aloha 🌺🏄🐬🐳
